version: 5.1.0
variant: default
logo: ''
head:
    favicon: /img/avatar.jpg
    manifest:
        name: Liang Blog
        short_name: Liang
        start_url: https://Liang5757.github.io/
        theme_color: '#3273dc'
        background_color: '#3273dc'
        display: standalone
        icons:
            -
                src: /img/avatar.jpg
                sizes: 144x144
                type: image/png
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/Liang5757
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/Liang5757
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: changyan
    app_id: cyvPeQjDi
    conf: prod_4423b2f156eaea470ca4247bc48505a9
sidebar:
    left:
        sticky: false
    right:
        sticky: true
widgets:
    -
        position: left
        type: profile
        author: Liang
        author_title: 
        location: Guangzhou, China
        avatar: /img/avatar.jpg
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/Liang5757
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/Liang5757
            Email:
                icon: fas fa-envelope
                url: mailto:1036933225@qq.com
    -
        type: toc
        position: right
        index: false
        collapsed: true
        depth: 3
    -
        position: left
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
excerpt_length: 400
